### ISSUE TITLE
Mastodon Collaborative - Plugins for Sharing a Mastodon Project via GitHub / GitLab

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon-tomancak#42]
**Part of #15**

# User Story

A Mastodon user would like to be able to store a Mastodon project to a git repository and clone a git repository to its local machine

# Acceptance criteria

* Mastodon plugin that allows to upload a Mastodon project to a gitlab/github server.
* Mastodon plugin that allows to clone a Mastodon project from a gitlab/github server.
* Mastodon plugin can read either an ssh-key or an access-token
* Mastodon plugin can be configured either via UI or via config-file where to find the ssh-key or access-token

# TODOs

* [x] Create Plugin
* [x] Plugin can read credentials
* [x] Plugin can push
* [x] Plugin can clone
* [x] UI components

**Comment by maarzt** [comment]
This functionality is available in https://github.com/maarzt/mastodon-git
